# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: myAgentPool

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.14'

  - script: |
      make install
    displayName: 'Install dependencies'

  - script: |
      make lint
    displayName: 'Lint with pylint'

  - script: |
      make test
    displayName: 'Test with pytest'